<?php


namespace common\widgets;


use yii\base\Widget;

class ButtonWidget extends Widget
{
    public $text;
    public $classes;
    public $type;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return '<button type="'.$this->type.'" class="'.$this->classes.'">'.ucfirst($this->text).'</button>';
    }

}