<?php

namespace common\widgets;

use yii\base\Widget;


class LoginFormWidget extends Widget
{

    public $action = '/user/login';
    public $id = 'login-form';

    public function run()
    {

        parent::run(); // TODO: Change the autogenerated stub
        $html = '
              <h2>Login Form</h2>
              <hr>
             <form action="'.$this->action.'" id="'.$this->id.'" method="POST">
              <div class="form-group field-loginform-username">
                <label for="registrationform-username">Email address</label>
                <input type="email" class="form-control" id="registrationform-username" placeholder="Email" name="LoginForm[username]" aria-required="true">
                <div class="help-block"></div>
              </div>
              <div class="form-group field-loginform-password">
                <label for="registrationform-password">Password</label>
                <input type="password" class="form-control" id="registrationform-password" placeholder="Password" name="LoginForm[password]" aria-required="true">
                <div class="help-block"></div>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Remember Me?
                </label>
              </div>
              <button type="submit" class="btn btn-primary" name="login">Login</button>
            </form>
        ';
        return $html;
    }

}