<?php


namespace frontend\widgets;


use yii\base\Widget;

class HelloWidget extends Widget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('test');
    }

}