<?php


namespace frontend\widgets;


use yii\base\Widget;
use yii\helpers\Html;

class SimpleWidget extends Widget
{
    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->message === null) {
            $this->message = 'Welcome Guest';
        }
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return Html::tag('h1', $this->message);
    }

}